### ISSUE TITLE
Error: Failed to prepare build: "vsphere-iso" 4 errors occurred

### ISSUE THREAD

**Issue by patsevanton** [guillermo-musumeci/packer-vsphere-iso-linux#3]
packer build centos-vsphere.json
Error: Failed to prepare build: "vsphere-iso"

4 errors occurred:
        * Deprecated configuration key: 'disk_size'. Please call `packer fix` against
your template to update your template to be compatible with the current version
of Packer. Visit https://www.packer.io/docs/commands/fix/ for more detail.
        * Deprecated configuration key: 'disk_thin_provisioned'. Please call `packer
fix` against your template to update your template to be compatible with the
current version of Packer. Visit https://www.packer.io/docs/commands/fix/ for
more detail.
        * Deprecated configuration key: 'network'. Please call `packer fix` against
your template to update your template to be compatible with the current version
of Packer. Visit https://www.packer.io/docs/commands/fix/ for more detail.
        * Deprecated configuration key: 'network_card'. Please call `packer fix`
against your template to update your template to be compatible with the current
version of Packer. Visit https://www.packer.io/docs/commands/fix/ for more
detail.

==> Wait completed after 4 microseconds

==> Builds finished but no artifacts were created.

**Comment by patsevanton** [comment]
packer version 1.6.4

**Comment by guillermo-musumeci** [comment]
The code is for Packer 1.5.x

**Comment by patsevanton** [comment]
Thanks

**Comment by guillermo-musumeci** [comment]
Run packer fix to convert the code to packer 1.6.x
